<a href="https://colab.research.google.com/github/Yazanmy/ML/blob/master/Exercises_(Important_Python_Packages).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
Ex1: Create a program that asks the user to enter their
name and their age. Print out a message addressed to them
that tells them the year that they will turn 100 years old.
```



In [64]:
import datetime

name = input("Your Name : ")
age = int(input("Your age : "))
date = datetime.datetime.now()
print ("Hello ",name, "in"  , 100- age + int(date.year) )


Your Name : Yazan
Your age : 21
Hello  Yazan in 2098


```
Ex3: Take a list, say for example this one: a = [1, 1, 2, 3, 5, 8,
13, 21, 34, 55, 89] and write a program that prints out all
the elements of the list that are less than 5.
```


In [65]:
a = [1, 1, 2, 3, 5, 8,13, 21, 34, 55, 89]
for x in a :
  if x<5 :
    print (x)

1
1
2
3


```
Ex5: Take two lists, say for example these two: a = [1, 1, 2, 3,
5, 8, 13, 21, 34, 55, 89] and b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
11, 12, 13] and write a program that returns a list that
contains only the elements that are common between the
lists (without duplicates). Make sure your program works on
two lists of different sizes.
```


In [66]:
a = [1, 1, 2, 3,5, 8, 13, 21, 34, 55, 89] 
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13]
print (set(a) &  set(b))

both=[]

if len(a)<len(b) :
  for i in b :
    if i in a and i not in both :
      both.append(i)
      
if len(b)<len(a):
  for i in a :
    if i in b and i not in both :
      both.append(i)

print(both)      

{1, 2, 3, 5, 8, 13}
[1, 2, 3, 5, 8, 13]


```
Ex28: Implement a function that takes as input three
variables, and returns the largest of the three. Do this
without using the Python max() function!

```


In [67]:
def fun(a,b,c):
  if a>b and a>c:
    return(a)
   
  if b>a and b>c:
    return(b)
  
  if c>a and c>b:
    return c
  
print(fun(5,9,7))  

9


~~~
Class 9: Write a Python class which has two
methods get_String and print_String. get_String
accept a string from the user and print_String print
the string in upper case.
~~~

In [89]:
class myclass():
  def __init__(self):
        self.Name = ""
      
  def  get_String(self):
    self.Name =input()
  
  def print_String(self):
    print(self.Name.upper())

S= myclass()    
S.get_String()
S.print_String()


yt
YT




```
Class 10: Write a Python class named Rectangle
constructed by a length and width and a method
which will compute the area of a rectangle
```



In [82]:
class Rectangle():

  def __init__(self,length,width):
      self.length=length
      self.width=width
     
  def computeArea(self):
     return self.length*self.width
      

Rectangle=Rectangle(5,10)
print(Rectangle.computeArea())

50


~~~
NumPy 3: Create a 3x3 matrix with values ranging from 2 to 10.
~~~

In [87]:
import numpy as np
array=np.arange(2,11,1).reshape(3,3)
print(array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


~~~
NumPy 73: Write a Python program to create an array of (3, 4) shape,
multiply every element value by 3 and display the new array.
~~~


In [93]:
import numpy as np
array=np.ones((3,4),np.int16)
print(array*3)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


```
Pandas DataFrame 4 and 5: Write a Python program to get the first 3 rows
and the 'name' and 'score' columns from the following DataFrame.
```

In [110]:
import pandas as pd

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine','James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin','Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8,19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes','no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data)
print(df.ix[0:3,['name','score']])

        name  score
0  Anastasia   12.5
1       Dima    9.0
2  Katherine   16.5
3      James    NaN


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':
